server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://picpo.top:3000/CrowdOS_Test?serverTimezone=GMT%2B8
    username: root  #数据库
    password: root #密码
